
Vagrant.configure("2") do |config|

  config.vm.box = '{{ box }}'
  config.vm.communicator = '{{ communicator }}'


  config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
     vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = "8192"
     vb.cpus = 4
  end

end
